### ISSUE TITLE
.rubocop.yml Metrics/BlockLength cop not recognized

### ISSUE THREAD

**Issue by erikdstock** [rubyide/vscode-ruby#132]
### Your environment

- `vscode-ruby` version: 
- Ruby version: 2.3.3
- VS Code version: 1.10.2
- Operating System: osx
- Hardware (optional): 

Make sure you have `ruby`, `ruby-debug-ide` and `ruby-debug-basex19` installed before submitting your issue -- thank you !

### Expected behavior
No annoying alert popping up  at top that says
'Warning: unrecognized cop Metrics/BlockLength found in <cwd>/app/.rubocop.yml'

### Actual behavior
That alert does keep popping up

### Steps to reproduce the problem
I am running a project out of docker-compose so this .rubocop file is nested in the ./app folder. the config in question is:
```yml
Metrics/BlockLength:
  ExcludedMethods:
    - describe
    - it
    - configure
```
