### ISSUE TITLE
Help with remote debug on docker container

### ISSUE THREAD

**Issue by pvm** [rubyide/vscode-ruby#220]
- `vscode-ruby` version: 0.15.0
- Ruby version: 2.4.2
- VS Code version:  1.17.2
- Operating System: Ubuntu 16.04

First, sorry if I created this issue on a wrong place.

So, I have my project on docker. I do not have a ruby installed on my machine, just on docker.
I'm trying to make the debugger work with this containers without any success. Anyone can provide me some help?
Here are my files:
Dockerfile:
```
FROM ruby:2.4

ENV APP_ROOT /app
ENV BUNDLE_PATH /bundle

COPY . $APP_ROOT

RUN apt-get update -qq && apt-get install -y build-essential libpq-dev

WORKDIR $APP_ROOT

CMD ['rails', 's', '-p', '3000', '-b', '0.0.0.0']
```
```yml
version: '3'

services:
  db:
    image: postgres
    container_name: ged.db
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=6266
      - POSTGRES_DB=ged_backend_development    
  api:
    build: .
    container_name: ged.api
    command: ./bin/start.sh
    ports:
      - "3000:3000"
      - "1234:1234"
      - "26162:26162"
    volumes:
      - ./src:/app
    links:
      - db
    depends_on:
      - db
    environment:
      - RAILS_ENV=development
      - PORT=3000
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=ged_backend_development
      - DB_USER=postgres
      - DB_PSWD=6266
```
Docker Compose file:

Start.sh:
```shell
#!/bin/bash
bundle check || bundle install --jobs 20 --retry 5

if [ -f tmp/pids/server.pid ]; then
  rm -f tmp/pids/server.pid
fi

bin/rails s -p $PORT -b 0.0.0.0 -e $RAILS_ENV
```

launch.json:
```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Listen for rdebug-ide",
      "type": "Ruby",
      "request": "attach",
      "cwd": "${workspaceRoot}/src",
      "remoteHost": "127.0.0.1",
      "remotePort": "1234",
      "remoteWorkspaceRoot": "/app",
      "showDebuggerOutput": true
    },
    {
      "name": "Rails server",
      "type": "Ruby",
      "request": "launch",
      "cwd": "${workspaceRoot}",
      "program": "${workspaceRoot}/bin/rails",
      "args": [
        "server"
      ]
    },
    {
      "name": "RSpec - all",
      "type": "Ruby",
      "request": "launch",
      "cwd": "${workspaceRoot}",
      "program": "${workspaceRoot}/bin/rspec",
      "args": [
        "-I",
        "${workspaceRoot}"
      ]
    },
    {
      "name": "RSpec - active spec file only",
      "type": "Ruby",
      "request": "launch",
      "cwd": "${workspaceRoot}",
      "program": "${workspaceRoot}/bin/rspec",
      "args": [
        "-I",
        "${workspaceRoot}",
        "${file}"
      ]
    },
    {
      "name": "Cucumber",
      "type": "Ruby",
      "request": "launch",
      "cwd": "${workspaceRoot}",
      "program": "${workspaceRoot}/bin/cucumber"
    }
  ]
}
```
