### ISSUE TITLE
VSCode (stable and insiders) doesn't format my code (rubocop installed and problems in code well detected).

### ISSUE THREAD

**Issue by johnunclesam** [rubyide/vscode-ruby#226]
### Your environment

- `vscode-ruby` version: 0.15.0
- Ruby version: ruby 2.4.2p198 (2017-09-14 revision 59899) [x64-mingw32]
- VS Code version: 1.18.1 and 1.19.0-insider 
- Operating System: Windows 10 latest

### Expected behavior

"Format Document" (Alt+Shift+F on Windows) should work.

### Actual behavior

It doesn't work.

### Steps to reproduce the problem

I have:

`rubocop -V`
`0.51.0 (using Parser 2.4.0.2, running on ruby 2.4.2 x64-mingw32)`

with .rubocop.yml:

```
Layout/EndOfLine:
  EnforcedStyle: lf

Style/Documentation:
  Enabled: true

Rails:
  Enabled: true
```

also tried with:

```
Layout/EndOfLine:
  EnforcedStyle: lf

Style/Documentation:
  Enabled: true

Rails:
  Enabled: true

Lint/DefEndAlignment:
  Enabled: true
```

but nothing. I have this in `.vscode/settings.json`:

```
"ruby.lint": {
    "reek": true,
    "rubocop": true,
    "ruby": true,
    "fasterer": true,
    "debride": {
      "lint": true,
      "rails": true
    }
  }
```

It well detects problems in my code.

**What is wrong?**
