### ISSUE TITLE
.rubocop.yml exclude doesn't work.

### ISSUE THREAD

**Issue by ghost** [rubyide/vscode-ruby#359]
### Your environment

- `vscode-ruby` version: 0.18.0
- Ruby version: ruby 2.4.4p296 (2018-03-28 revision 63013) [x64-mingw32]
- VS Code version: 1.24.1 and 1.25.0-insider 
- Operating System: Windows 10 latest

### Expected behavior

`.rubocop.yml` like this should work:

```
AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'db/**'
    - '**/Gemfile'
    - 'Gemfile.lock'
```

### Actual behavior

`db/schema.rb`, `Gemfile` and `Gemfile.lock` being rubocopped.

Via `rubocop db` it works. So, **it's a bug**?
