### ISSUE TITLE
Fails with inherit_gem config

### ISSUE THREAD

**Issue by dachinat** [rubyide/vscode-ruby#457]
### Your environment

- `vscode-ruby` version:
- Ruby version: 2.5.1
- Ruby version manager (if any): rvm 1.29.7
- VS Code version: 1.32
- Operating System: macOS
- Using language server? no

### Expected behavior

Should format

.rubocop.yml:

```
inherit_gem:
  rubocop-rails_config:
    - config/rails.yml

AllCops:
  TargetRubyVersion: 2.5.1
```

### Actual behavior

`rubocop failed with code=2`
