### ISSUE TITLE
MethodLength does not count spaces

### ISSUE THREAD

**Issue by Xoph** [rubyide/vscode-ruby#46]
### Your environment
- `vscode-ruby` version: 0.5.2
- Ruby version: 2.1.0
- VS Code version: 1.3.1
- Operating System: Windows 7 64-bit
### Expected behavior

No warning when I add:

`# rubocop: disable MethodLength`
### Actual behavior

Unnecessary disabling of 'Metrics\MethodLength'. (Lint/UnneededDisable)
### Steps to reproduce the problem

Use the following block of code. Run RuboCop from the command prompt command line. Notice there are 17 lines (8 of which are blank), so it triggers the MethodLength warning.

```
  def a
    puts '1'

    puts '2'

    puts '3'

    puts '4'

    puts '5'

    puts '6'

    puts '7'

    puts '8'

    puts '9'
  end

```

Adding the disable for MethodLength:
`# rubocop: disable MethodLength`
removes the warning from the command-prompt window, but VS Code then gives the following warning (and highlights the line above):

Unnecessary disabling of 'Metrics\MethodLength'. (Lint/UnneededDisable)

It seems to be an issue caused by the empty lines in the method. If I put 17 lines of actual code, neither VS Code or the command-line report an error.

Christoph
GE Healthcare

**Comment by HookyQR** [comment]
@Xoph: Blank lines aren't considered code, so neither should be triggering `Metrics\MethodLength`, and thus both should trigger `Lint/UnneededDisable`. I can't duplicate the situation where running on the command line provides different results. Are you running the command from the project directory? If you have a `.rubocop.yml` file in either the project root, or the directory where the file resides, you may get varying results - assuming one of them changes the trigger for either of these cops.

**Comment by Xoph** [comment]
Here is my .rubop.yml file:
````
inherit_from:
- ../../.rubocop.yml
Style/FileName:
    Enabled: false

# In this cookbook we are allowing the module length to be larger than the standard allows
# so that we can encode some PowerShell blocks in the module to enable lazy loading.
Metrics/ModuleLength:
  Max: 500
````
And here is the one that in inherits from:
````
Metrics/LineLength:
  Max: 600
Metrics/AbcSize:
  Max: 40
Documentation:
  Enabled: false
MethodLength:
  Max: 15
ClassLength:
  Max: 250
Style/WordArray:
  Enabled: false
RedundantReturn:
  Enabled: false
Metrics/ModuleLength:
  Max: 300
````

But none of these should impact spacing, right?
