### ISSUE TITLE
Lint errors shown does not match bundle exec rubocop command.

### ISSUE THREAD

**Issue by RileyMathews** [rubyide/vscode-ruby#495]
### Your environment

- `vscode-ruby` version: 0.23.0
- Ruby version: 2.4.6
- Ruby version manager (if any): Running inside docker
- VS Code version: 1.36.0
- Operating System: MacOS
- Using language server? (eg `useLanguageServer` is true?): No

### Expected behavior
That lint errors underlined in the text editor window would match the errors caught by `bundle exec rubocop`, including configuration by inherited gems.

### Actual behavior
In the editor, I see an error in my RSpec blocks for 'block has too many lines'. When I run `bundle exec rubocop` on the same file. I do not see the errors.

*This and the next section should include screenshots, code samples, console output, etc. The more information we have to reproduce the better!*

My rubocop config looks like this.
```yaml
AllCops:
  TargetRubyVersion: 2.4.6
  Exclude:
    - 'node_modules/**/*'

inherit_gem:
  ramsey_cop:
    - default.yml

require: rubocop-performance
```

The ramsey_cop gem is an internal gem we have that has the following config in its rules. 
```yaml
Metrics/BlockLength:
  Exclude:
    - config/initializers/*
    - config/routes.rb
    - Gemfile
    - spec/**/*
    - test/**/*
    - "*.gemspec"
    - "**/*.rake"
```

My vscode config for anything related to ruby is this.
```json
{
  "[ruby]": {
    "editor.formatOnSave": true
  },
  "ruby.format": "rubocop",
  "editor.formatOnSaveTimeout": 2500,
  "ruby.codeCompletion": false,
  "ruby.intellisense": "rubyLocate",
  "ruby.lint": {
    "rubocop": true
  },
  "ruby.useBundler": true
}
```

I also use the solargraph extension for goto definition. All of this is running inside of a docker container running centos, and running vscode through the docker remote development extension.

EDIT: I have discovered that if I put the configuration from our inherited gem straight into the local rubocop configuration file. The linting matches up one for one. I think now that this is definitely an issue with rubocop configuration inheritance, and how the extension interacts with it.
