### ISSUE TITLE
Option to specify the path to the rules file

### ISSUE THREAD

**Issue by lobo-tuerto** [rubyide/vscode-ruby#745]
### Your environment

- `vscode-ruby` version: 0.28.1
- Ruby version: 3.0.1
- Ruby version manager (if any): asdf
- VS Code version: 1.56.2
- Operating System: macOS Big Sur 11.4
- Using language server? Yes

### Expected behavior

It'd be helpful to be able to specify the configuration file for rubocop.
Just like you can do in the CLI:

```text
Usage: rubocop [options] [file1, file2, ...]
    -c, --config FILE                Specify configuration file.
```

For example in overcommit we have:

```yml
PreCommit:
  RuboCop:
    enabled: true
    on_warn: fail # Treat all warnings as failures
    command: ['bin/rubocop', '-c', '.rubocop.yml']
```

As you can see I'm able to pass the confg file in there.

I think it would be useful to be able to specify that in settings.json like this:

```js
  "ruby.lint": {
    "rubocop": {
      // ...
      "configPath": ".rubocop.yml" // or some other place / name relative to project root
    }
  }
```

### Actual behavior

Config path cannot be specified :(
Thus, vscode-ruby is triggering a lot of false positives since it cannot read our config file.

*This and the next section should include screenshots, code samples, console output, etc. The more information we have to reproduce the better!*
*If this is a syntax highlighting report please include a code sample that can be quickly copied and pasted!*
